name: "Build Android APK"
on:
  push:
    branches: [ "master", "main" ]
  workflow_dispatch:

jobs:
  build:
    name: Export APK
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup Android SDK and Editor Settings
        run: |
          mkdir -p ~/.android
          keytool -keyalg RSA -genkeypair -alias androiddebugkey -keypass android -keystore ~/.android/debug.keystore -storepass android -dname "CN=Android Debug,O=Android,C=US" -validity 9999
          
          # หา Java 17 path
          JAVA_PATH=$(dirname $(dirname $(readlink -f $(which javac))))
          echo "Found Java at $JAVA_PATH"
          
          # สร้าง config ให้ Godot ชี้หา Android SDK สำเร็จรูปใน docker
          mkdir -p ~/.config/godot
          cat <<EOF > ~/.config/godot/editor_settings-4.tres
          [gd_resource type="EditorSettings" format=3]
          [resource]
          export/android/android_sdk_path = "/usr/lib/android-sdk"
          export/android/java_sdk_path = "$JAVA_PATH"
          export/android/debug_keystore = "/root/.android/debug.keystore"
          export/android/debug_keystore_user = "androiddebugkey"
          export/android/debug_keystore_pass = "android"
          export/android/force_system_user = false
          EOF

      - name: Create Export Folder
        run: mkdir -v -p build/android

      - name: Build Android APK
        run: godot -v --headless --export-debug "Android" build/android/RiseOfGummy.apk

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: RiseOfGummy-Android-APK
          path: build/android/RiseOfGummy.apk
